import type { Metadata } from "next";
import { Epilogue, Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

import Header from "@/components/layout/Header";
import Providers from "@/components/Providers";
import Footer from "@/components/layout/Footer";
import ScrollToTop from "@/components/ui/ScrollToTop";


const clashDisplay = localFont({
    src: [
        {
            path: '../../public/assets/fonts/ClashDisplay-Semibold.woff2',
            weight: '600',
            style: 'normal'
        }
    ],
    variable: '--font-clash',
    display: 'swap',
})

const epilogue = Epilogue({
    display: 'swap',
    variable: "--font-epilogue",
    subsets: ["latin"],
    weight: ['400', '500', '600', '700'],
});

const inter = Inter({
    display: 'swap',
    variable: "--font-inter",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
    return (
        <html lang="en">
            <body className={`${clashDisplay.variable} ${epilogue.variable} ${inter.variable} antialiased`}>
                <Providers>
                    <Header />
                    <main className="mt-15">{children}</main>
                    <Footer/>
                </Providers>
                <ScrollToTop/>
            </body>
        </html>
    );
}
