import type { Metadata } from "next";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import ScrollToTop from "@/components/ui/ScrollToTop";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({children,}: Readonly<{children: React.ReactNode;}>) {
    return (
        <>
            <Header />
            <main>{children}</main>
            <Footer/>
            <ScrollToTop/>
        </>
    );
}
